version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install -e src/
          name: Local pip install of package
      - run:
          command: python -m pytest
          name: Test
      - run:
          name: Create package distribution
          command: python src/setup.py sdist
      - persist_to_workspace:
          root: dist
          paths:
            - .
  pypi:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Upload package
          command: build_scripts/upload.sh

workflows:
  main:
    jobs:
      - build-and-test
      - pypi:
          context: pypi
          requires:
            - build-and-test
          filters:
            branches:
              only: master
